name: GitHub Actions Demo
on:
  push:
    branches:
    - 'main'
jobs:
  deploy_to_clouds:
    runs-on: self-hosted
    name: Apply the decK configuration
    steps:
      - uses: actions/checkout@v2
      #
      # can be used to ensure no changes have occurred outside of our repo
      # - run: deck konnect diff --non-zero-exit-code
      #
      - run: deck konnect sync